[% MSG = {
   module_name = "Adlibris Acquisition"
   configuration = "Configuration"
   home = "Home"
   plugins = "Plugins"
   save_configuration = "Save configuration",
   receive_order = "Receive Order",
   receive_url_heading = "URL to the Receive Order Service",
   receive_url_text = "The account at Adlibris should be configured to send the order data to this url:",
   receive_url_info = "If the above URL does not start with https:// or http://, or if the link doesn't work due to incorrect domain name, you will need to set the system preference staffClientBaseURL.",
   demo_mode = "Enable demo mode"
}%]