[% MSG = {
   module_name = "Adlibris Beställning"
   configuration = "Konfiguration"
   home = "Tillbaka"
   plugins = "Plugins"
   save_configuration = "Spara konfiguration",
   receive_order = "Ta emot beställning",
   receive_url_heading = "URL till tjänst för att ta emot beställning.",
   receive_url_text = "Hos Adlibris skall följande URL läggas in för att ta emot beställningen i Koha:",
   receive_url_info = "Om ovanstående URL inte börjar med https:// eller http://, eller om länken inte fungerar på grund av felaktigt domännamn, behöver systempreferensen staffClientBaseURL ställas in.",
   demo_mode = "Aktivera demodata"
}%]